apiVersion: v1
kind: ConfigMap
metadata:
  name: predis-conf
  namespace: "default"
  labels:
    app: predis-conf
data:
  redis.conf: |-
    appendonly yes
    protected-mode no
    port 6379
    dir /data

