apiVersion: v1
kind: ConfigMap
metadata:
  name: predis-scripts
  namespace: "default"
  labels:
    app: predis-scripts
data:
  run.sh: |-
    #!/bin/bash
    cp /config/redis.conf /data/redis.conf
    echo "..........$HOSTNAME"
    if [[ "$HOSTNAME" == "predis-sts-0" ]]; then
      echo "..........$HOSTNAME"
      exec redis-server /data/redis.conf
    else
      echo -e "\nslaveof predis-sts-0.predis-svc.default.svc.cluster.local 6379" >>/data/redis.conf
      exec redis-server /data/redis.conf
    fi

