apiVersion: v1
kind: ConfigMap
metadata:
  name: predis-scripts
  namespace: "default"
  labels:
    app: predis-scripts
data:
  run.sh: |-
    #!/bin/bash
    cp /config/redis.conf /data/redis.conf

    echo "..........$HOSTNAME"

    sentinel_info_command="redis-cli -h sentinel-svc.default.svc -p 26379 SENTINEL get-master-addr-by-name mymaster"
    REDIS_SENTINEL_INFO=($($sentinel_info_command))
    REDIS_MASTER_HOST=${REDIS_SENTINEL_INFO[0]}
    REDIS_MASTER_PORT_NUMBER=${REDIS_SENTINEL_INFO[1]}

    echo "----------$REDIS_MASTER_HOST-------------"

    echo "----------$REDIS_MASTER_PORT_NUMBER------"

    echo "-----------------------------------------"

    if [[ ${#REDIS_SENTINEL_INFO[@]} == 0 && $HOSTNAME == "predis-sts-0" ]]; then
      exec redis-server /data/redis.conf
    else
      ping_command="timeout 2 redis-cli -h $REDIS_MASTER_HOST -p 6379 ping"
      PONG=($($ping_command))

      if [[ $PONG == "PONG" ]]; then
        echo -e "\nslaveof $REDIS_MASTER_HOST $REDIS_MASTER_PORT_NUMBER" >> /data/redis.conf
        exec redis-server /data/redis.conf
      else
        if [[ $HOSTNAME == "predis-sts-0" ]]; then
          exec redis-server /data/redis.conf
        else
          echo -e "\nslaveof $REDIS_MASTER_HOST $REDIS_MASTER_PORT_NUMBER" >> /data/redis.conf
          exec redis-server /data/redis.conf
        fi
        remove_master_from_0th_sentinel = "redis-cli -h sentinel-sts-0.sentinel-svc.default.svc -p 26379 SENTINEL REMOVE mymaster"
        add_master_with_0th_sentinel    = "redis-cli -h sentinel-sts-0.sentinel-svc.default.svc -p 26379 SENTINEL MONITOR mymaster predis-sts-0.predis-svc.default.svc 6379 2"

        remove_master_from_1th_sentinel = "redis-cli -h sentinel-sts-1.sentinel-svc.default.svc -p 26379 SENTINEL REMOVE mymaster"
        add_master_with_1th_sentinel    = "redis-cli -h sentinel-sts-1.sentinel-svc.default.svc -p 26379 SENTINEL MONITOR mymaster predis-sts-0.predis-svc.default.svc 6379 2"

        remove_master_from_2th_sentinel = "redis-cli -h sentinel-sts-1.sentinel-svc.default.svc -p 26379 SENTINEL REMOVE mymaster"
        add_master_with_2th_sentinel    = "redis-cli -h sentinel-sts-1.sentinel-svc.default.svc -p 26379 SENTINEL MONITOR mymaster predis-sts-0.predis-svc.default.svc 6379 2"

        REMOVE_MASTER_FROM_0TH_SENTINEL=($($remove_master_from_0th_sentinel))
        ADD_MASTER_WITH_OTH_SENTINEL=($($add_master_with_0th_sentinel))

        REMOVE_MASTER_FROM_0TH_SENTINEL=($($remove_master_from_1th_sentinel))
        ADD_MASTER_WITH_OTH_SENTINEL=($($add_master_with_1th_sentinel))

        REMOVE_MASTER_FROM_0TH_SENTINEL=($($remove_master_from_1th_sentinel))
        ADD_MASTER_WITH_OTH_SENTINEL=($($add_master_with_1th_sentinel))

      fi
    fi

#    if [[ "$HOSTNAME" == "predis-sts-0" ]]; then
#      echo "..........$HOSTNAME"
#      exec redis-server /data/redis.conf
#    else
#      echo -e "\nslaveof predis-sts-0.predis-svc.default.svc.cluster.local 6379" >>/data/redis.conf
#      exec redis-server /data/redis.conf
#    fi

