apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-scripts
  namespace: "default"
  labels:
    app: sentinel-scripts
data:
  run.sh: |-
    #!/bin/bash
    cp /config/sentinel.conf /data/sentinel.conf

    echo " got scripts............"
    exec redis-sentinel /data/sentinel.conf


